#!/bin/zsh
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
SOURCE_DIR="$REPO_ROOT/hooks" # If we want to vendor hooks

mkdir -p "$HOOKS_DIR"

# Pre-flight checks
if [[ -z "${BEADS_DIR:-}" ]]; then
    echo "❌ FATAL: BEADS_DIR not set in environment."
    echo "This is a V5 requirement. Add it to ~/.zshrc and export it."
    exit 1
fi

if [[ -d "$REPO_ROOT/.beads" ]]; then
    echo "⚠️  WARNING: Legacy .beads/ directory found in repo root."
    echo "Please remove it: rm -rf $REPO_ROOT/.beads"
    echo "V5 requires all Beads state to live in BEADS_DIR."
    # Non-blocking for now, but we'll enforce it in the hook
fi

install_hook() {
    local name=$1
    local content=$2
    local target="$HOOKS_DIR/$name"
    
    echo "Installing $name hook..."
    rm -f "$target"
    cat > "$target" <<EOF
#!/bin/zsh
# AUTO-GENERATED BY setup-git-hooks.sh

# V5 GUARD: Refuse to run if BEADS_DIR is missing or if local .beads exists
if [[ -z "\${BEADS_DIR:-}" ]]; then
    echo "❌ [V5 HOOK] PUSH BLOCKED: BEADS_DIR not set in environment."
    exit 1
fi

if [[ -d "\$(git rev-parse --show-toplevel)/.beads" ]]; then
    echo "❌ [V5 HOOK] PUSH BLOCKED: Local .beads/ directory detected."
    echo "Migration Required: Move state to \$BEADS_DIR and delete local .beads/"
    exit 1
fi

$content
EOF
    chmod +x "$target"
}

# Pre-push hook (The main enforcer)
# Runs beads-sync and quality checks before push
install_hook "pre-push" '
# 1. Sync Beads (external DB)
echo "🔄 [V5 HOOK] Syncing Beads..."
bd sync

# 2. DX Check (Fast validation)
if [[ -f "./Makefile" ]] && grep -q "ci-lite:" Makefile; then
    echo "🧪 [V5 HOOK] Running ci-lite..."
    make ci-lite
else
    echo "⚠️  [V5 HOOK] No ci-lite target found, skipping validation"
fi

echo "✅ [V5 HOOK] Pre-push checks passed"
'

# Post-merge hook (Auto-refresh)
install_hook "post-merge" '
echo "🔄 [V5 HOOK] Post-merge sync..."
# If this repo has AGENTS.md, regenerate it
if [[ -f "./Makefile" ]] && grep -q "regenerate-agents-md:" Makefile; then
    make regenerate-agents-md
fi

# Fetch baseline if possible
if [[ -f "./Makefile" ]] && grep -q "baseline-sync:" Makefile; then
    # Usually schedule-only, but can run on merge
    # make baseline-sync
fi

echo "✅ [V5 HOOK] Post-merge complete"
'

echo "✅ Git hooks installed successfully."
